apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fun-deployment
  labels:
    app: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: 
        ports:
        - containerPort: 
